In [1]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [2]:
data = {
    'City': ['Pune', 'Mumbai', 'Pune', 'Delhi'],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Age': [23, 25, 22, 30]
}

df = pd.DataFrame(data)
print(df)

     City  Gender  Age
0    Pune    Male   23
1  Mumbai  Female   25
2    Pune  Female   22
3   Delhi    Male   30

In [4]:
encoder = OneHotEncoder(sparse=False)

encoded_data = encoder.fit_transform(df[['City', 'Gender']])

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [5]:
encoded_df = pd.DataFrame(
    encoded_data,
    columns=encoder.get_feature_names_out(['City', 'Gender'])
)

print(encoded_df)

NameError: name 'encoded_data' is not defined

In [7]:
final_df = pd.concat([encoded_df, df[['Age']]], axis=1)
print(final_df)

   City_Delhi  City_Mumbai  City_Pune  Gender_Female  Gender_Male  Age
0         0.0          0.0        1.0            0.0          1.0   23
1         0.0          1.0        0.0            1.0          0.0   25
2         0.0          0.0        1.0            1.0          0.0   22
3         1.0          0.0        0.0            0.0          1.0   30

# Another WAY

In [6]:
import pandas as pd

data = {
    'City': ['Pune', 'Mumbai', 'Pune', 'Delhi'],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Age': [23, 25, 22, 30]
}

df = pd.DataFrame(data)
df

     City  Gender  Age
0    Pune    Male   23
1  Mumbai  Female   25
2    Pune  Female   22
3   Delhi    Male   30

In [7]:
df_dummies = pd.get_dummies(df).astype(int)

In [8]:
# Another WAY
df_dummies = pd.get_dummies(df, drop_first=True)

bool_cols = df_dummies.select_dtypes(include='bool').columns
df_dummies[bool_cols] = df_dummies[bool_cols].astype(int)

In [9]:
df_dummies

   Age  City_Mumbai  City_Pune  Gender_Male
0   23            0          1            1
1   25            1          0            0
2   22            0          1            0
3   30            0          0            1

# Another WAY

In [21]:
import pandas as pd

data = {
    'City': ['Pune', 'Mumbai', 'Pune', 'Delhi'],
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'Age': [23, 25, 22, 30]
}

df = pd.DataFrame(data)
df

     City  Gender  Age
0    Pune    Male   23
1  Mumbai  Female   25
2    Pune  Female   22
3   Delhi    Male   30

In [24]:
#best WAY
cat_cols = df.select_dtypes(include=['object', 'category']).columns

df_dummies = pd.get_dummies(df, columns=cat_cols, drop_first=True)

df_dummies = df_dummies.astype(int)

In [25]:
df_dummies

   Age  City_Mumbai  City_Pune  Gender_Male
0   23            0          1            1
1   25            1          0            0
2   22            0          1            0
3   30            0          0            1